### ISSUE TITLE
Make it work with plugin() syntax

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-nested#10]
Right now if I do

```js
postcss().use(postcssNested()); // notice parens
```

I get a TypeError (object is not a function) because the module only returns an object with a postcss method, instead of returning a *function* (which also has a postcss property for no-parens syntax).

**Comment by ai** [comment]
Done bdc38c3

**Comment by ai** [comment]
I am waiting for Travis CI result and then I will release 0.2.2.

**Comment by davidtheclark** [comment]
Cool, thanks.

**Comment by ai** [comment]
Travis CI is slow today. I released 0.2.2.

**Comment by ai** [comment]
BTW, 4.1 plugin syntax will be:

```js
.use(plugin)             // default options
.use(plugin({ one: 1 })) // with options
```

**Comment by davidtheclark** [comment]
Ok. That's pretty much what I was expecting based on other discussions. You could also do 
```js
.use(plugin()) // default options
```
... right?

**Comment by ai** [comment]
Yeap, `.use(plugin())` will be possible too.
