### ISSUE TITLE
PostCSS plugin postcss-nested requires PostCSS 8

### ISSUE THREAD

**Issue by AliceMakk** [postcss/postcss-nested#100]
Hello there,
I did set up postcss 8v but still getting that error when running my app:
**Error: PostCSS plugin postcss-nested requires PostCSS 8.**

my package.json
```
...
    "postcss": "^8.1.1",
    "postcss-nested": "^5.0.1",
...
```

Would be happy if somebody could guide me how to fix that problem please.

**Comment by ai** [comment]
In what type of project do you use PostCSS? How do you run PostCSS?

Gatsby, Create React App, Webpack, Gulp?

**Comment by AliceMakk** [comment]
Oh, thanks for your quick reply.
I use Ember framework and the error happens when I run my instance with 'ember s'.

**Comment by ai** [comment]
Seems like Ember still using PostCSS 7. Adding PostCSS 8 to your project’s dependencies will not update PostCSS inside your builder.

Can you look at Ember GitHub repository. Maybe they already have PostCSS 8 issue where they working on the problem?

**Comment by AliceMakk** [comment]
Ah, I see.
Well ok, will have a look there than. :)
Thanks
