### ISSUE TITLE
Nested "&" at the tail not resolved correctly

### ISSUE THREAD

**Issue by rluba** [postcss/postcss-nested#115]
The following code:
```css
.a { .b { .c & {} } }
```

… gets transformed into:

```css
.a .c .b {}
```

… but it should be:
```css
.c .a .b {}
```

…because the `&` references the _whole_ current selector, not just the immediate parent. (Sass generates the correct output.)

**Comment by ai** [comment]
Agree. Please send PR.

**Comment by rluba** [comment]
👍 Already working on it…

**Comment by ai** [comment]
Feel free to ask questions about the current architecture
