### ISSUE TITLE
Nested media queries

### ISSUE THREAD

**Issue by silvenon** [postcss/postcss-nested#12]
It would be so awesome if this plugin could combine `@media` queries like Sass does:

```scss
.foo {
  @media (min-width: 400px) {
    @media (max-width: 800px) {
      // ...
    }
  }
}
```

Would result into:

```css
@media (min-width: 400px) and (max-width: 800px) {
  .foo {
    // ...
  }
}
```

Is this feature within the scope of the plugin?

**Comment by ai** [comment]
Yeap. Nice feature. But I didn’t promise a time, when I add it :).

**Comment by silvenon** [comment]
Ok :wink:

**Comment by ai** [comment]
As I understand current outputt:

```css
@media (min-width: 400px) {
  @media (max-width: 800px) {
    .foo {
    }
  }
}
```

works too. So it is a optimization and not part of this plugin.

**Comment by ai** [comment]
But you should write to @ben-eb [cssnano](https://github.com/ben-eb/cssnano). It looks like good work for minifier.

**Comment by silvenon** [comment]
I don't think nested media queries have an adequate [browser support](http://stackoverflow.com/questions/11746581/nesting-media-rules-in-css) yet, but ok.

**Comment by ai** [comment]
@silvenon even for fallback reason it will be a different plugin.

Do you need a help with this separated plugin? I will be jst in few lines of code.

**Comment by silvenon** [comment]
You're right, it's not within the scope. Nevermind :grin:
