### ISSUE TITLE
"> *" errors after 5.0.3

### ISSUE THREAD

**Issue by abstractball** [postcss/postcss-nested#121]
example code: 
```
&.has-icon {
  @apply inline-flex justify-center items-center;

  /* Have the icon not ride on the edge of a label */
  > * {
    @apply mx-1
  }
}
```

If I stay at 5.0.3 of the package, no error will occur, however if I go above 5.0.3 I will receive the error until I comment out the > * part.
Using Next.js 10 and Typescript 4.2

> error - ./project/styles/components.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-5-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-5-2!./proejct/styles/components.css)
TypeError: Cannot set property 'parent' of undefined

**Comment by ai** [comment]
Can you try `& > *`?
