### ISSUE TITLE
I cannot @apply classes with nested elements

### ISSUE THREAD

**Issue by SergiArias** [postcss/postcss-nested#124]
Hello!

I come from tailwind docs where they recommend this plugin so I don't have to use scss.

The problem (that doesn't happen in scss) is that if I create a class like so and then apply it:

```postcss
  .btn-outline {
    &::before {
      @apply opacity-0 scale-x-50 duration-500;
    }
  }

  .btn-outline-primary {
    @apply btn-outline text-primary;
  }
```
Then the @apply doesn't work, but the btn-outline class works. I guess that the problem is the order in which each plugin is processing the info. 
Is this a bug or a expected behaviour? Is there any workaround?

In scss it works because postcss is applied after scss has generated the css file.

**Comment by ai** [comment]
It happens because we need to migrate `postcss-nested` to new PostCSS 8 events (`Rule` instead of `OnceExit`), but I do not have time to do it.

I will be glad if somebody will send a PR.

**Comment by SergiArias** [comment]
I don't even know where to start, but I hope someone who does can PR. Thanks!!

**Comment by SergeAstapov** [comment]
Looks like `RuleExit` was replaced by `Rule` in #116 (Big Thanks to @rluba), which wad part of v5.0.3 release.


@SergiArias mind to re-check on your side? (TBH not sure it's the fix for the same issues, but really *looks similar*)

**Comment by ai** [comment]
Can you try 5.0.6 release. The bug may be fixed by @bsak-shell in https://github.com/postcss/postcss-nested/pull/137

**Comment by maranomynet** [comment]
This seems to be fixed.
