### ISSUE TITLE
Incorrect output when using Tailwindcss JIT production build

### ISSUE THREAD

**Issue by therealgilles** [postcss/postcss-nested#126]
The issue with a testcase is described here: https://github.com/tailwindlabs/tailwindcss/issues/3964

**Comment by ai** [comment]
I will not have on this week. Feel free to send PR.

**Comment by therealgilles** [comment]
How do I go about finding out where the problem lies?

The issue is related to the use how the comma, i.e. this will produce incorrect results:

```CSS
	.a .b label,
	.c label {
		input[type='search'] {
			@apply bg-white;
		}
	}
```

but this works:

```CSS
	.a .b label {
		input[type='search'] {
			@apply bg-white;
		}
	}
	.c label {
		input[type='search'] {
			@apply bg-white;
		}
	}
```

PS: Sorry for the weird example, I am mimicking what I have in my css file.

**Comment by ai** [comment]
> How do I go about finding out where the problem lies?

Add test and then start to debug with `console.log` or IDE debugger.

Sorry, I have no better ideas for now.

**Comment by therealgilles** [comment]
Thank you. From my analysis, the problem lies with Tailwindcss and not postcss-nested. If I disable the tailwindcss plugin, the output looks correct. I'm going to close this issue.
