### ISSUE TITLE
5.0.0+ breaks `ember-css-modules`

### ISSUE THREAD

**Issue by emattias** [postcss/postcss-nested#140]
When using `postcss-nested@4.2.3` (latest v4) together with [ember-css-modules](https://github.com/salsify/ember-css-modules) the classes get generated differently than when using `postcss-nested@5.0.6` (latest v5).

See this issue for more info and reproduction repos: https://github.com/salsify/ember-css-modules/issues/253

**Comment by emattias** [comment]
@ai What do you think about what @dfreeman says here: https://github.com/salsify/ember-css-modules/issues/253#issuecomment-975476928 ?

**Comment by ai** [comment]
Yeap, the `Once` plugins is a very fast way to convert PostCSS plugin, but it doesn’t help with plugin compatibility.

The idea is to move to true event system with `Rule`, etc.
