### ISSUE TITLE
Strange behaviour on unwrapping nested elements

### ISSUE THREAD

**Issue by talyguryn** [postcss/postcss-nested#146]
Found strange behaviour on my code and tried to test on example. Correct me if I'm wrong please.

## Code from readme

![image](https://user-images.githubusercontent.com/15259299/182963728-23eb2a0b-aa5b-4d8b-8dd9-5da3217988d4.png)

## ✅ OK for `postcss-nested@5.0.1`

![image](https://user-images.githubusercontent.com/15259299/182963795-d393cacd-9d07-4cb7-8d6b-8fd1e43a9a61.png)

## ❌ WRONG for `postcss-nested@5.0.2`-`postcss-nested@5.0.6`

![image](https://user-images.githubusercontent.com/15259299/182963675-1991edde-4896-49ac-a2d8-3f68a4d89735.png)

## .postcssrc.yml

```
plugins:
  # Consumes files by @import rule
  # https://github.com/postcss/postcss-import
  postcss-import: {}

  # Convert modern CSS into something most browsers can understand
  # https://github.com/csstools/postcss-preset-env
  postcss-preset-env:
    # Polyfill CSS features
    # https://github.com/csstools/postcss-preset-env#stage
    #
    # List of features with levels: https://cssdb.org/
    stage: 0

    # Define polyfills based on browsers you are supporting
    # https://github.com/csstools/postcss-preset-env#browsers
    browsers:
      - 'last 2 versions'
      - '> 1%'

    # Instruct all plugins to omit pre-polyfilled CSS
    # https://github.com/csstools/postcss-preset-env#preserve
    preserve: false

  # Nested rules unwrapper
  # https://github.com/postcss/postcss-nested
  #
  # As you know 'postcss-preset-env' plugin has an ability to process
  # 'postcss-nesting' feature but it does not work with BEM
  # Report: https://github.com/csstools/postcss-preset-env/issues/40
  postcss-nested: {}

  # Compression tool
  # https://github.com/cssnano/cssnano
#  cssnano: {}
```

**Comment by ai** [comment]
Can you post an input example as a text, so I can copy paste it?

**Comment by talyguryn** [comment]
hm, sorry. might be not `postcss-nested` problem.  i think this is my bad with the wrong order of plugins. 

![image](https://user-images.githubusercontent.com/15259299/183308728-b986990a-a034-4fec-b57d-a564c4c1fa49.png)

![image](https://user-images.githubusercontent.com/15259299/183308754-5988d848-e57b-4ecb-991b-400c4fb09ad0.png)

but it is still strange to get this unpacking by `postcss-preset-env` 🤔

**Comment by ai** [comment]
Seems like you are using `postcss-nesting` (another plugin, it used by `postcss-preset-env`). It based on CSS spec and has another syntax. You need `@nest body.is-dark &` (if your selector started not from `&` you need `@nest` prefix).
