### ISSUE TITLE
Tag mismatch

### ISSUE THREAD

**Issue by simPod** [postcss/postcss-nested#152]
npmjs.com contains 6.0.1

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/327717/219941978-123b5ebf-1cf1-4ae0-a520-cf266eca3cdf.png">

This repo contains 6.1

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/327717/219941982-12f5676a-9781-4478-97d9-caa53da324ce.png">

What is correct?

**Comment by ai** [comment]
Fixed
