### ISSUE TITLE
Is PostCSS known for being slow on Windows?

### ISSUE THREAD

**Issue by zilti** [postcss/postcss-nested#156]
We have a project here using postcss for tailwind. It runs very fast (as expected) on Linux and macOS, but we noticed that it's very slow on Windows in our case - Sometimes what takes a second or less on Linux takes 30s or even over a minute on Windows.

Is this a known thing? Are there "hacks"/"workarounds" to get better performance on Windows?

**Comment by ai** [comment]
1. This is nested syntax repo. You should ask in `postcss/postcss`
2. I don’t use Windows and can’t help you here. If you are using Docker, the problem will be with Docker (Windows has no native support). In general Node.js community just don’t care about Windows support and performance. It is better to switch to UNIX.

**Comment by zilti** [comment]
Oh, sorry for that! :sweat_smile:
