### ISSUE TITLE
nesting causes last style in parent selector to not have a semicolon

### ISSUE THREAD

**Issue by tehOPEologist** [postcss/postcss-nested#18]
```body {
	color: #f00;
	h1 {
		color: #0f0;
		h2 {
			color: red;
		}
	}
}```

renders to:

```body {
	color: #f00
}
body h1 {
	color: #0f0
}
body h1 h2 {
	color: red;
}```

**Comment by ai** [comment]
Can you mark your code examples by <code>```</code>?

**Comment by tehOPEologist** [comment]
yeah sorry, i figured there was a better way to do that.  one moment.

**Comment by tehOPEologist** [comment]
this is embarrassing, it doesn't want to mark properly.  do i put them on each line that should be in a group of code?  or beginning / end?

**Comment by ai** [comment]
@tehOPEologist put in before and after your code example.

**Comment by tehOPEologist** [comment]
there we go.  the new lines were messing it up.  edited for code highlighting

**Comment by tehOPEologist** [comment]
looks like minifications do the same thing, i guess i just didn't realize it until i did some small test styling.  closing
