### ISSUE TITLE
body element rendered differently

### ISSUE THREAD

**Issue by ninjapiraatti** [postcss/postcss-nested#24]
body{
        color: #000;
        .nested{
            color: #fff;
        }
    }

renders:

    body{color:#000; color:#fff;}.nested{}

But if I replace body element with div or any class it renders correctly.

**Comment by ai** [comment]
Note, that this issue is not hhigh priority :).

I think to refactor raw properties in 5.0, but before it PostCSS has some issues in code style formation keeping.

**Comment by ai** [comment]
Can’t reproduce. In my case I got:

```css
body{
    color: #000;
}
body .nested{
    color: #fff;
}
```

Maybe some tool before/after PostCSS broke it?
