### ISSUE TITLE
a suggest when use @media query

### ISSUE THREAD

**Issue by rguanghui** [postcss/postcss-nested#27]
hi, when i use postcss-nested like this
```
@media (--pc-wide-viewport), ie8wide {
  .profile {
    width: 500px;
  }
}
```

it give me

```
@media (--pc-wide-viewport), ie8wide {
  .profile {
    width: 500px;
  }
}
```

and i'm expect
```
@media (--pc-wide-viewport) {
  .profile {
    width: 500px;
  }
}

ie8wide .profile {
  width: 500px;
}
```

hope to support this :smile:

**Comment by ai** [comment]
Why yuo expect this behaviour from postcss-nested? Docs do not talk about it. Sass do not support this too.

**Comment by rguanghui** [comment]
ok, this just my personal thoughts and i don't go to check whether sass is support this.

i just think it will save my code and strength when do this to support ie8. :dog:

**Comment by ai** [comment]
@rguanghui what abut making oown plugin? `postcss-mq-selector`. It will run before `postcss-nested` and will uncompress only at-rules and selectors?
