### ISSUE TITLE
Nesting depth warning

### ISSUE THREAD

**Issue by ahmedelgabri** [postcss/postcss-nested#28]
So one of the bad things about nesting that it can get out of hand if you work in a team with different CSS skill levels. And soft rules like _3 levels max_ is not really effective. How about an option to warn or even limit the nesting depth?

```js
postcss([ require('postcss-nested')({ nestingDepth: 3  }) ]
```

**Comment by ai** [comment]
Awesome idea. But it should be done in seperated linter. Each PostCSS plugin must do only one task, like in UNIX pholosophy.

Ask [stylelint](https://github.com/stylelint/stylelint) team. It is a modular PostCSS based linter. So it is very easy to add other linter.

/cc @MoOx @davidtheclark

**Comment by ahmedelgabri** [comment]
@ai Already done that :) https://github.com/stylelint/stylelint/issues/291

**Comment by davidtheclark** [comment]
Ha. Yeah, @ai: I referred him to you. I wasn't sure about integrating plugin-specific rules into stylelint ...

Maybe this would be a use-case for the custom rule functionality that we want to (eventually) implement in stylelint.
