### ISSUE TITLE
Select an element with multiple classes

### ISSUE THREAD

**Issue by alexbooker** [postcss/postcss-nested#42]
If we want to select an element with two classes we can write `.foo.bar { }`.

Is it possible to express `.foo.bar { }` using **`postcss-nested`**?

```sass
.foo {
   .bar { }  
    // ... compiles into ".foo .bar" (which is correct) but is there a way to emit ".foo.bar"?
}
```

At the moment my work around is to write a separate sector:

```sass
&__link {
  display: block;
  &:focus,
  &:hover {
    background-color: #272727;
    color: white;
    text-decoration: none;
  }
}
&__link.active {
  background-color: #272727;
  color: white;
  text-decoration: none;
}
```

... I would prefer it if I could nest the selector however.

Thanks :+1:

**Comment by ai** [comment]
```css
.foo {
  &.bar {
  }
}
```

**Comment by alexbooker** [comment]
It seems so obvious now. Thanks, @ai!
