### ISSUE TITLE
Nested @keyframes are not moved to root after compiling

### ISSUE THREAD

**Issue by AntonioRedondo** [postcss/postcss-nested#43]
As [SASS](http://sassbreak.com/nested-keyframe-rules-sass/) and [LESS](http://lesscss.org/features/#features-overview-feature-nested-directives-and-bubbling) do, when there is a `@keyframes` at-rule nested within a selector body it will be moved to the CSS file root once the original SCSS/LESS files is compiled. However, with PreCSS and PostCSS this looks to not be implemented and `@keyframes` will remain nested within the selector body. Hence the animation won't run on browsers.

```
.block {
	&__element {
		width: 20px;
		height: 20px;
		animation: 2.5s linear infinite spin;

		@keyframes spin {
			0% { transform: rotate(0deg) translateX(20px); }
			100% { transform: rotate(360deg) translateX(20px); }}
		}
	}
}
```
will compile into

```
.block__element {
	width: 20px;
	height: 20px;
	animation: 2.5s linear infinite spin;

	@keyframes spin {
		0% { transform: rotate(0deg) translateX(20px); }
		100% { transform: rotate(360deg) translateX(20px); }}
	}
}
```
rather than
```
.block__element {
	width: 20px;
	height: 20px;
	animation: 2.5s linear infinite spin;
}

@keyframes spin {
	0% { transform: rotate(0deg) translateX(20px); }
	100% { transform: rotate(360deg) translateX(20px); }}
}
```

**Comment by ai** [comment]
Hm. Why do you need so?  What will be a semantic, that keyframe is inside rule?

**Comment by AntonioRedondo** [comment]
It's a very handy option. You keep the `@keyframes` next to the `animation` CSS statement since pretty much never animations are reusable.

**Comment by ai** [comment]
Why you can't keep keyframes next to rule but in root level? 😉 Could you show big example? Maybe we need better solution.

**Comment by AntonioRedondo** [comment]
Putting `@keyframes` at the root but next to the selector doesn't work as well as having the `@keyframes` nested. This is specially relevant when using BEM, the Block have many Elements or many Modifiers, then the `@keyframes` for a given Element or Modifier would need to be far from the `animation` statement.
```
.block {
    &__element1 {
        animation: 2.5s linear infinite spin1;
    }
    &__element2 {
        animation: 2.5s linear infinite spin2;
    }
    &__element3 {
        animation: 2.5s linear infinite spin3;
    }
}

@keyframes spin1 {
  0% { transform: rotate(0deg) translateX(20px); }
  100% { transform: rotate(360deg) translateX(20px); }}
}
@keyframes spin2 {
  0% { transform: rotate(0deg) translateX(20px); }
  100% { transform: rotate(360deg) translateX(20px); }}
}
@keyframes spin3 {
  0% { transform: rotate(0deg) translateX(20px); }
  100% { transform: rotate(360deg) translateX(20px); }}
}
```
isn't as practical as
```
.block {
    &__element1 {
        animation: 2.5s linear infinite spin1;
        @keyframes spin1 {
            0% { transform: rotate(0deg) translateX(20px); }
            100% { transform: rotate(360deg) translateX(20px); }}
        }
    }
    &__element2 {
        animation: 2.5s linear infinite spin2;
        @keyframes spin2 {
            0% { transform: rotate(0deg) translateX(20px); }
            100% { transform: rotate(360deg) translateX(20px); }}
        }
    }
    &__element3 {
        animation: 2.5s linear infinite spin3;
        @keyframes spin3 {
            0% { transform: rotate(0deg) translateX(20px); }
            100% { transform: rotate(360deg) translateX(20px); }}
        }
    }
}
```
On longer real statements the difference in readability and cohesion is considerably higher.

**Comment by ai** [comment]
I have a better and more PostCSS-ish way. What do you think about this syntax:

```css
.block {
    &__element1 {
        animation: 2.5s linear infinite {
            0% { transform: rotate(0deg) translateX(20px); }
            100% { transform: rotate(360deg) translateX(20px); }}
        }
        …
    }
}
```

You don’t need to create a keyframes names for this animation-for-one-element-only case. So, maybe we should write a PostCSS plugin that will generate keyframes name for you?

What do you think about this plugin?

**Comment by AntonioRedondo** [comment]
Ummm, your proposal of putting the keyframes without name next to the `animation` rule looks to me a very good idea.

I have no time to implement something of the kind at the moment though.

**Comment by ai** [comment]
Feel free to ask any question
