### ISSUE TITLE
comment bug (with px2rem)

### ISSUE THREAD

**Issue by banricho** [postcss/postcss-nested#44]
### Input

```PostCSS
.captcha-form {
  padding: 5px 10px 5px 20px;
  border: 1px solid #e0e0e0; /* no */

  input {
    width: 300px;
  }
  img {
    display: block;
  }
}
```

### Output

```PostCSS
.captcha-form {
  padding: 5px 10px 5px 20px;
  border: 1px solid #e0e0e0;
}
/* no */
.captcha-form input {
  width: 300px;
}
.captcha-form img {
  display: block;
}
```

`/* no */` comment is for [px2rem](https://github.com/songsiqi/px2rem). Cause of this bug, px2rem will transform the original value.

Thanks :)

**Comment by ai** [comment]
Could you put comment before `;`?

**Comment by banricho** [comment]
@ai 
I have tried that, but px2rem can't discern it.
Thanks for your reply.

**Comment by ai** [comment]
Sorry, I think you should `px2rem` to have comment inside.
