### ISSUE TITLE
Feature Request: Add Information On Configuring stylelint

### ISSUE THREAD

**Issue by Undistraction** [postcss/postcss-nested#49]
Using [stylelint](https://github.com/stylelint/stylelint)'s default settings means it will choke on these nested selectors. Please add information to the README on how to configure stylelint to correctly validate these nested selectors. The rule can be found [here](https://stylelint.io/user-guide/rules/selector-nested-pattern/), but by default it doesn't support the features added by postcss-nested. It would be helpful to publish a regex that satisfies them.

**Comment by ai** [comment]
Please, send PR, because I am not really sure about what Stylelint integration problem did you have.

**Comment by Undistraction** [comment]
Using stylelint's default settings with postcss-nested results in linting errors as the syntax used by postcss-nested isn't supported by the [relevant rule](https://stylelint.io/user-guide/rules/selector-nested-pattern/). The rule uses a regex to validate nested selectors and only supports using `hover` and `focus`:
```
&:hover {}
&:focus {}
``` 

Given that postcss-nested supports various additional ways to nest, I am suggesting adding a regex which covers them to the documentation, as anyone using postcss-nested alongside stylelint will encounter this problem. I haven't managed a suitable regex so far.

**Comment by ai** [comment]
Why you think this docs should be here and not in `selector-nested-pattern` rule docs?

**Comment by Undistraction** [comment]
Because `selector-nested-pattern` is a generalised rule for nesting. It is designed to be flexible and cover any implementation, of which postcss-nested is just one. They are only going to document a sensible default, not a separate regex for every pre/post processor's own flavour of nesting. Given that stylelint is becoming the standard for linting I think it makes sense to help people using postcss-nested to correctly lint for its nested selectors.

**Comment by ai** [comment]
OK, what exactly don’t work? Could you show some examples, I still don’t get what is a problem and how it is relevant with `postcss-nested`.

**Comment by Undistraction** [comment]
So if I take the example from your README:

```
.phone {
  &_title {
    width: 500px;

    @media (max-width: 500px) {
        width: auto;
    }
    body.is_dark & {
        color: white;
    }
  }
  img {
      display: block;
  }
}
```

This generates the following linting errors:

1. Expected nested selector "body.is_dark &" to match specified patter (selector-nesting-pattern)
2. Expected nested selector "img" to match specified patter (selector-nesting-pattern)

**Comment by ai** [comment]
But if you will write:

```css
.phone {
  &:hover {
  }
}
```

Everything will work?

**Comment by Undistraction** [comment]
Yep. Because the default Regex allows it.

**Comment by ai** [comment]
Yeap, and why we need docs in `postcss-nested`? `selector-nesting-pattern` has a docs how to change this regexp.

**Comment by Undistraction** [comment]
I'm suggesting you document the regex that would correctly validate the types of nested selector that postcss-nested enables.

**Comment by ai** [comment]
This rule is to limit some nested rules. What is a point to use regexp for *any* nested selectors? If you don’t want to lint nested selectors, just disable this rule.

The reason of this rule is to force some specific nested style. For example, in BEM you should use nesting only for `&:hover`, `&:active` or modification. If you want to prohibit all other nested rules, you can enable this plugin.
