### ISSUE TITLE
:global and nested classes?

### ISSUE THREAD

**Issue by bytasv** [postcss/postcss-nested#51]
Hello,

I have this snippet:
```css
:global .theme-class {
  .button { ... }

  .button--primary { ... }
}
```
In browser I get this output:
```css
.theme-class {
  .button_34hj34 { ... }

  .button--primary_34hj34 { ... }
}
```
Since this is not a standard CSS (nesting is not supported) this doesn't give me result that I want. What I want is output like this:

```css
.theme-class .button_34hj34 { ... }
.theme-class .button--primary_34hj34 { ... }
```

I'm using webpack, with PostCSS loader

What am I doing wrong?

**Comment by bytasv** [comment]
It appears that I mixed and actually used `postcss-nesting` instead of `postcss-nested`...

**Comment by a-x-** [comment]
Hm, I cannot write like this in both `postcss-nested` and `postcss-nesting`:

```css
:global {
  .smtg {}
}
```
