### ISSUE TITLE
TypeError: after.after is not a function

### ISSUE THREAD

**Issue by krambertech** [postcss/postcss-nested#54]
My webpack config:

```js
           {
                test: /\.css$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'style-loader',
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            importLoaders: 1,
                            modules: true,
                            localIdentName: '___[name]__[local]___[hash:base64:5]',
                        },
                    },
                    {
                        loader: 'postcss-loader',
                    },
                ],
            },
```

PostCSS plugins:

```
        options: {
            postcss: [
                postcssFunctions({
                    functions: require('../app/styles/colorFunctions.js'),
                }),
                postcssVars({
                    variables() {
                        return variables;
                    },
                }),
                postcssNested(),
                postcssAssets({
                    loadPaths: ['static/'],
                }),
                autoprefixer({
                    browsers: [
                        'last 3 version',
                        'ie >= 11',
                    ],
                }),
            ],
        },
```

**Comment by ai** [comment]
This error happens because you use `postcss-nested` with PostCSS 5.0, but latest `postcss-nested` support only PostCSS `>= 6.0.0`

**Comment by ai** [comment]
Update your PostCSS

**Comment by ai** [comment]
Also next time always add error stacktrace

**Comment by krambertech** [comment]
Thanks for a quick reply and the amazing work you are doing on postcss and stylelint!

**Comment by ai** [comment]
=^_^=

**Comment by jfstephe** [comment]
For gulp, the minimum version you want is 7:
npm install gulp-postcss@7.0.0 --save-dev

**Comment by olifer655** [comment]
```
Your current PostCSS version is 5.2.17, but postcss-nested uses 6.0.8. Perhaps this is the source of the error below.
```
but actuality,my PostCSS version is 6.0.8

**Comment by ai** [comment]
@olifer655 it is npm, different packages could use different dependencies.

**Comment by Danetag** [comment]
I still have the issue, and my PostCSS version is 6.0.9... Any update/lead?

**Comment by ai** [comment]
@Danetag in npm some d libraries could use own version of dependencies. So even if you wrote PostCSS 6 in your package.json, gulp-postcss could user old version.

npm has a command to show all dependencies tree. You can use it (sorry, I am from phone and can't give you exact command).

**Comment by Danetag** [comment]
Thank you, going to check that out :)

**Comment by langri-sha** [comment]
@ai strange, would be great if all the PostCSS packages had a `{peerDependency}` instead of working like this.

**Comment by Alex1990** [comment]
I came cross the similar issue, then I upgrade the `postcss` and`postcss-loader`to the latest version, it works.
