### ISSUE TITLE
Error: after.after is not a function

### ISSUE THREAD

**Issue by retyui** [postcss/postcss-nested#59]
Node#after is deprecated. Use Node#raws.after
[09:21:25] gulp-notify: [Css] Error: after.after is not a function
[09:21:25] gulp-notify: [Error running notifier] Could not send message: not found: notify-send

```bash
Linux 3.19.0-30-generic #34~14.04.1-Ubuntu SMP Fri Oct 2 22:09:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ yarn --version 0.24.5
$ node -v v8.0.0
-------------------
or Win 10, node 8
```
dome repo https://github.com/retyui/xgulp/tree/nested
1. **clone** and **checkout** **nested** branch
2. `yarn`
3. `./node_modules/.bin/gulp css`

**Comment by ai** [comment]
Dublicate https://github.com/postcss/postcss-nested/issues/54

Update your PostCSS for PostCSS 6.0.

**Comment by retyui** [comment]
Yes, i am install new version `yarn add gulp-postcss@7 postcss@6; rm -rf node_modules; yarn`
https://github.com/retyui/xgulp/commit/6d24fed3f09d5a6333ad51af9cb4a4bcecefc6a3
But the error remained
```bash
Node#after is deprecated. Use Node#raws.after
[09:49:17] gulp-notify: [Css] Error: after.after is not a function
```

**Comment by ai** [comment]
Could you check `node_modules` content and be sure, that do don’t have 2 versions of PostCSS?

**Comment by andreasvirkus** [comment]
Also getting this error. Using it with postcss-loader in a Vue project. My versions:
```
npm list postcss
.../code/project
├─┬ autoprefixer@7.1.4
│ └── postcss@6.0.11

npm list postcss-nested
.../code/project
└── postcss-nested@2.1.2
```
