### ISSUE TITLE
CSS Nesting Module Level 3

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-nested#6]
http://tabatkins.github.io/specs/css-nesting/

```sass
  table.colortable {{
    td {
      text-align:center;
      {&.c { text-transform:uppercase }}
      {&:first-child, &:first-child + td { border:1px solid black }}
    }
    th {
      text-align:center;
      background:black;
      color:white;
    }
  }}
```

output

```sass
  table.colortable td {
    text-align:center;
  }
  table.colortable td.c {
    text-transform:uppercase;
  }
  table.colortable td:first-child, table.colortable td:first-child+td {
    border:1px solid black;
  }
  table.colortable th {
    text-align:center;
    background:black;
    color:white;
  }
```

**Comment by ai** [comment]
This is unofficial draft. I do not see any advantages of two `{{` instead of one `{`.

**Comment by yisibl** [comment]
Yes, I agree. 

@tabatkins

**Comment by shinnn** [comment]
@yisibl Why did you mention him?

**Comment by yisibl** [comment]
He is this specification authors. At the same time is also very powerful CSS editor.

**Comment by shinnn** [comment]
@yibisi I know. I meant it's better to open an issue on the spec [repo](https://github.com/tabatkins/specs) instead of here.

**Comment by ai** [comment]
@shinnn for current issue @tabatkins can tell about current status of this spec and his advices of indent rules implementation in PostCSS

**Comment by shinnn** [comment]
@ai Got it.

**Comment by tabatkins** [comment]
The spec explains why the second `{` is needed: <http://tabatkins.github.io/specs/css-nesting/#the-nested-block>

**Comment by MichielBijl** [comment]
Will this syntax be implemented? Would be nice to have official support.

**Comment by ai** [comment]
Sass syntax. You can use [postcss-nesting](https://github.com/jonathantneal/postcss-nesting) for tabaskin spec.

Docs already have a mention right after examples.
