### ISSUE TITLE
Changing the default "collapsing" behavior

### ISSUE THREAD

**Issue by matthew-dean** [postcss/postcss-nested#78]
Could a feature be added to change the default behavior of nested selectors to not append a space? That is, have this:
```less
.a {
  .b { ... }
  :hover { ... }
}
```
compile to:
```css
.a.b { ... }
.a:hover { ... }
```
And then requiring `&` to include a space like:
```less
.a {
  & .b { ... }
  & :hover { ... }
}
```

Styled-components does something like this for pseudo-elements / pseudo-selectors. (Maybe an option to just select those? Or omit spaces from all?) See: https://www.styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting

**Comment by ai** [comment]
It is much easy to make fork of the plug-in with different behavior.

I will post a link to your solution.
