### ISSUE TITLE
Wrong compilation

### ISSUE THREAD

**Issue by smercadomx** [postcss/postcss-nested#83]
Since version 4.1.1 this:
```css
[aria-label=“”] { ...}
```

Is being compiled to this:
```css
[aria-label] { ...}
```

**Comment by ai** [comment]
Hi. Thanks for the report.

I am right now on vacation in the Atakama dessert. Can I ask you to help me with this and send PR?

**Comment by darotar** [comment]
As I see, since 4.1.2 this is already fixed

@smercadomx How it works for you now?
