### ISSUE TITLE
how do i do a child class?

### ISSUE THREAD

**Issue by chovy** [postcss/postcss-nested#86]
In sass I can do:

```
a {
  color: blue;

  &.active {
    color: green;  
  }
}
```

How would I do this with postcss-nested?

**Comment by ai** [comment]
In the same way. Do you have any problem with the same code in PostCSS with postcss-nested?

**Comment by chovy** [comment]
I think its a problem with svelte and rollupjs not picking up the css correctly.

**Comment by ai** [comment]
👍

**Comment by ai** [comment]
Wish you a good luck in configuring them
